services:
    db:
        hostname: db
        container_name: moniswap-fi-db
        image: mongo:6-jammy
        volumes:
            - dbdata:/data/db
        networks:
            - db
            - api
    main:
        hostname: main
        container_name: moniswap-fi-tokenlist-server
        ports:
            - 1998:1998
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - api
volumes:
    dbdata:
        external: false
networks:
    api:
        external: false
